export const FETCH_ALBUMS = 'FETCH_ALBUMS'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_ERROR = 'FETCH_ALBUMS_ERROR'

export const ADD_ALBUM = 'ADD_ALBUM'
export const ADD_ALBUM_SUCCESS = 'ADD_ALBUM_SUCCESS'
export const ADD_ALBUM_ERROR = 'ADD_ALBUM_ERROR'