export const FETCH_ARTISTS = 'FETCH_ARTISTS'
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTIST_SUCCESS'
export const FETCH_ARTISTS_ERROR = 'FETCH_ARTISTS_ERROR'

export const ADD_ARTIST = 'ADD_ARTIST'
export const ADD_ARTIST_SUCCESS = 'ADD_ARTIST_SUCCESS'
export const ADD_ARTIST_ERROR = 'ADD_ARTIST_ERROR '